Fix updaters 26 and 36 leaving dump inconsistent
They were updating some fields (namely filenames and filename schemas)
on some objects, but these fields were also used as keys in dictionary
relationships in other objects, and those keys weren't updated. When
importing an affected dump, one would get:

TypeError: Found incompatible key 'output_*.txt' for value <cms.db.submission.File object at 0x7fe668fe6ba8>; this collection's keying function requires a key of 'output___2a.txt' for this value.

or:

TypeError: Found incompatible key 'output_%s.txt' for value <cms.db.submission.File object at 0x7fffec608f60>; this collection's keying function requires a key of 'output___s.txt' for this value.