Fix drop_db
It failed with the following error when trying to unlink too many large
objects:

psycopg2.OperationalError: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.